server:
  port: 8081
  servlet:
    context-path: /service01
spring:
  application:
    name: service01
  config:
    import: configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
      
      
      spring:
      mail:
    host: smtp.gmail.com
    port: 587
    username: rahulkirar101214@gmail.com
    password: odwz pwaf riba icox